export const RARITY_COLORS = {
  common:    '#9ca3af',
  rare:      '#3b82f6',
  legendary: '#f97316',
};

export const ACHIEVEMENTS = [
  { id: 'first_export',        name: 'First Steps',          icon: '🚀', rarity: 'common',    xp: 50,   description: 'Export your first thumbnail' },
  { id: 'ten_exports',         name: 'Thumbnail Machine',    icon: '⚡', rarity: 'rare',      xp: 200,  description: 'Export 10 thumbnails' },
  { id: 'fifty_exports',       name: 'Content Factory',      icon: '🏭', rarity: 'legendary', xp: 500,  description: 'Export 50 thumbnails' },
  { id: 'first_text',          name: 'Word Wizard',          icon: '✍️', rarity: 'common',    xp: 25,   description: 'Add your first text layer' },
  { id: 'five_layers',         name: 'Layer Cake',           icon: '🎂', rarity: 'common',    xp: 30,   description: 'Have 5 layers on one canvas' },
  { id: 'used_color_grade',    name: 'Color Grader',         icon: '🎨', rarity: 'common',    xp: 40,   description: 'Apply a color grade' },
  { id: 'used_all_grades',     name: 'Palette Master',       icon: '🖌️', rarity: 'rare',      xp: 150,  description: 'Try all 20 color grades' },
  { id: 'template_applied',    name: 'Fast Starter',         icon: '📋', rarity: 'common',    xp: 30,   description: 'Use a template' },
  { id: 'bg_removed',          name: 'Cutout Artist',        icon: '✂️', rarity: 'rare',      xp: 100,  description: 'Remove a background' },
  { id: 'ai_generated',        name: 'AI Whisperer',         icon: '🤖', rarity: 'rare',      xp: 120,  description: 'Generate an AI image' },
  { id: 'thumbfriend_chat',    name: 'Got Feedback',         icon: '💬', rarity: 'common',    xp: 25,   description: 'Chat with ThumbFriend' },
  { id: 'ctr_score_70',        name: 'Click Magnet',         icon: '🧲', rarity: 'rare',      xp: 200,  description: 'Achieve a CTR score of 70+' },
  { id: 'ctr_score_90',        name: 'Thumbnail God',        icon: '👑', rarity: 'legendary', xp: 500,  description: 'Achieve a CTR score of 90+' },
  { id: 'streak_3',            name: 'Habit Forming',        icon: '🔥', rarity: 'common',    xp: 50,   description: '3-day editing streak' },
  { id: 'streak_7',            name: 'Week Warrior',         icon: '💪', rarity: 'rare',      xp: 150,  description: '7-day editing streak' },
  { id: 'streak_30',           name: 'Unstoppable',          icon: '⚡', rarity: 'legendary', xp: 600,  description: '30-day editing streak' },
  { id: 'night_owl',           name: 'Night Owl',            icon: '🦉', rarity: 'common',    xp: 40,   description: 'Edit after midnight' },
  { id: 'speed_demon',         name: 'Speed Demon',          icon: '💨', rarity: 'rare',      xp: 100,  description: 'Export within 3 minutes of starting' },
  { id: 'undo_master',         name: 'Undo Master',          icon: '↩️', rarity: 'common',    xp: 20,   description: 'Undo 10 times in one session' },
  { id: 'nice_exports',        name: 'Nice.',                icon: '😎', rarity: 'legendary', xp: 69,   description: 'Export exactly 69 thumbnails' },
  { id: 'rainbow_explosion',   name: 'Secret: Rainbow',      icon: '🌈', rarity: 'legendary', xp: 100,  description: 'Find the rainbow easter egg' },
  { id: 'konami_code',         name: 'Classic Gamer',        icon: '🎮', rarity: 'legendary', xp: 150,  description: 'Enter the Konami code' },
  { id: 'ufo_spotter',         name: 'UFO Spotter',          icon: '🛸', rarity: 'legendary', xp: 80,   description: 'Spot the UFO' },
  { id: 'midnight_editor',     name: 'Midnight Crunch',      icon: '🌙', rarity: 'rare',      xp: 75,   description: 'Edit exactly at midnight' },
  { id: 'youtube_connected',   name: 'Connected',            icon: '📺', rarity: 'rare',      xp: 100,  description: 'Connect your YouTube channel' },
  { id: 'face_enhanced',       name: 'Face Off',             icon: '✨', rarity: 'rare',      xp: 80,   description: 'Enhance a face with AI' },
  { id: 'style_transferred',   name: 'Style Thief',          icon: '🎭', rarity: 'common',    xp: 50,   description: 'Apply a creator style' },
  { id: 'referred_friend',     name: 'Recruiter',            icon: '🤝', rarity: 'rare',      xp: 200,  description: 'Refer a friend who signs up' },
  { id: 'showcase_submitted',  name: 'Show Off',             icon: '🏆', rarity: 'common',    xp: 60,   description: 'Submit to the showcase' },
  { id: 'pro_upgrade',         name: 'Going Pro',            icon: '⭐', rarity: 'legendary', xp: 300,  description: 'Upgrade to Pro' },
];
